# Generated by Django 4.2.6 on 2023-11-16 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0006_features_rename_title_song_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.color')),
            ],
        ),
        migrations.RemoveField(
            model_name='mymodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercolormusic',
            name='color',
        ),
        migrations.RemoveField(
            model_name='usercolormusic',
            name='music',
        ),
        migrations.RemoveField(
            model_name='usercolormusic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='song',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='song',
            name='features',
        ),
        migrations.AddField(
            model_name='song',
            name='preview_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.DeleteModel(
            name='UserColorMusic',
        ),
        migrations.AddField(
            model_name='assignedsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_app.song'),
        ),
        migrations.AddField(
            model_name='assignedsong',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_songs', to=settings.AUTH_USER_MODEL),
        ),
    ]
