# Generated by Django 4.2.6 on 2023-10-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0004_appuser_mymodel_user_alter_color_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.URLField(default=''),
        ),
    ]
