# Generated by Django 4.2.6 on 2023-11-10 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_app', '0005_song_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acousticness', models.FloatField(null=True)),
                ('danceability', models.FloatField(null=True)),
                ('energy', models.FloatField(null=True)),
                ('instrumentalness', models.FloatField(null=True)),
                ('liveness', models.FloatField(null=True)),
                ('loudness', models.FloatField(null=True)),
                ('speechiness', models.FloatField(null=True)),
                ('tempo', models.FloatField(null=True)),
                ('valence', models.FloatField(null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='album',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='audio_file',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='song',
            name='colors',
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.CharField(default='Unknown Song', max_length=100),
        ),
        migrations.AlterField(
            model_name='song',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='song',
            name='features',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='music_app.features'),
        ),
    ]
